name: Test Package
on:
    pull_request:
        branches:
            - 'master'
    push:
        branches:
            - 'master'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Use Node.js 12
          uses: actions/setup-node@v1
          with:
            node-version: 12
        - run: npm install
        - run: npm install jest-cli
        - run: npm ci
        - run: npm run build --if-present
        - run: npm test
